name: gro-early-learning-careers
services:
- name: web
  source_dir: /
  github:
    repo: your-github-username/gro-early-learning-careers
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    type: SECRET
  - key: OPENAI_API_KEY
    type: SECRET
  - key: SESSION_SECRET
    type: SECRET

databases:
- name: gro-careers-db
  engine: PG
  version: "15"
  size: db-s-dev-database
  num_nodes: 1